#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCZnEeJuLdEyadnAp5/ev71puvH1s4njhsz6AmVzH+Fycn8J2QmjJi2+DpsrP/oTwz98lXWcuviyx5crd9PEJ+ZO4VR7BGfVWnIekK/ozQEcB7wmspcaHKHUFRV8Dh2FDbXSphbPttlFQir15T8Q+kwc6KDQyH9/Q5C5SEAoXkE03pCf7an8xZRnTMIB6Fpf8SN1h/vlrr218sfw/9VYILxtA+552Jmjm0JsFFZqvHlxAk3C7vSLZupOdG5HXQucX/+mXbKBBNwa6nUbnnj2stlkSgMt7sdq+5OYArIlxNDPxMqXhGj4fIxjCzlndghSMLUYzg3ywussHBNWYifHsPF aws-key
packages:
  - apache2 
  - curl 
  - wget 
  - php 
  - libapache2-mod-php 
  - php-mysqli
  - adminer
write_files:
  - path: /var/www/html/info.php
    permissions: '0644'
    content: |
      <?php
        // Show all information, defaults to INFO_ALL
        phpinfo();
      ?>
  - path: var/www/html/db.php
    permissions: '0644'
    content: |
      <?php
        //database
        $servername = "172.31.10.14";
        $username = "admin";
        $password = "password";
        $dbname = "mysql";

        // Create connection
        $conn = new mysqli($servername, $username, $password, $dbname);
        // Check connection
        if ($conn->connect_error) {
                die("Connection failed: " . $conn->connect_error);
        }

        $sql = "select Host, User from mysql.user;";
        $result = $conn->query($sql);
        while($row = $result->fetch_assoc()){
                echo($row["Host"] . " / " . $row["User"] . "<br />");
        }
        //var_dump($result);
      ?>
runcmd:
  - sudo a2enconf adminer
  - sudo systemctl restart apache2