#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCZnEeJuLdEyadnAp5/ev71puvH1s4njhsz6AmVzH+Fycn8J2QmjJi2+DpsrP/oTwz98lXWcuviyx5crd9PEJ+ZO4VR7BGfVWnIekK/ozQEcB7wmspcaHKHUFRV8Dh2FDbXSphbPttlFQir15T8Q+kwc6KDQyH9/Q5C5SEAoXkE03pCf7an8xZRnTMIB6Fpf8SN1h/vlrr218sfw/9VYILxtA+552Jmjm0JsFFZqvHlxAk3C7vSLZupOdG5HXQucX/+mXbKBBNwa6nUbnnj2stlkSgMt7sdq+5OYArIlxNDPxMqXhGj4fIxjCzlndghSMLUYzg3ywussHBNWYifHsPF aws-key
ssh_pwauth: false
disable_root: false 
packages:  
  - mariadb-server
runcmd:
  - sudo mysql -sfu root  -e "GRANT ALL ON *.* TO 'admin'@'%' IDENTIFIED BY'password' WITH GRANT OPTION;"
  - sudo sed -i "s/127.0.0.1/0.0.0.0/g" /etc/mysql/mariadb.conf.d/50-server.cnf
  - sudo systemctl restart mariadb.service